### ISSUE TITLE
setup travis auth

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/github-base#15]

**Comment by doowb** [comment]
@jonschlinkert I changed the test auth file to also check for environment variables being set for github username and password.

You should be able to use [these steps](https://docs.travis-ci.com/user/encryption-keys/) to securely add your username and password to the `.travis.yml` file. I don't think I can do it since this repo is on your account.

**Comment by jonschlinkert** [comment]
will do, thanks!
