### ISSUE TITLE
Browser support.

### ISSUE THREAD

**Issue by AndersDJohnson** [jonschlinkert/github-base#8]
I'd like to look to see if we can get this working in the browser. It relies on simple-get which relies on Node http, so we may want to try building with browserify.
It'd be nice if a browser compatible version were published on npm.
Then I can use this in lieu of octokat.

**Comment by doowb** [comment]
Have you tried with browserify? I've used browserify to build a script that uses `github-base` so I could minify the code, but it was still running on node.

If it doesn't work after that in the browser, then you probably just have to replace `http` with a library that will work since everything else should be working fine.

If you get it working, it'd be great to see a recipe or a documentation update containing the settings you use for browserify.

**Comment by AndersDJohnson** [comment]
@doowb @jonschlinkert It doesn't work with webpack using babel as it's unable to statically analyze the dynamic `require` calls in the `lazy-cache` module which is a transitive dependency via the `use` module dependency.

**Comment by doowb** [comment]
@adjohnson916 you can use [unlazy-loader](https://github.com/doowb/unlazy-loader#usage) with webpack.

**Comment by jonschlinkert** [comment]
closing since this is more of an implementation question than a bug report or feature request
